#cloud-config
hostname: mariadb
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINH8qM6nWKA+kTwCmU8n8OqaXodQ1feToqa4tyIsguvQ alberto@debarg
chpasswd:
  expire: False
  users:
    - name: ubuntu
      password: asdasd
      type: text
