#cloud-config
hostname: apache2
users:
  - name: debian
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINH8qM6nWKA+kTwCmU8n8OqaXodQ1feToqa4tyIsguvQ alberto@debarg
chpasswd:
  expire: False
  users:
    - name: debian
      password: asdasd
      type: text


